//! Closed connection-artifact vocabulary for Operator executors.
//!
//! These are production identities, not slogans. A require/produce string
//! that does not parse is a catalog defect.

use crate::foundation::error::{BrainError, BrainResult};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactKind {
    ActivationEvents,
    ActivationSteeringShadowArtifact,
    ActiveAdapterSelection,
    ActivityObservation,
    AdapterBankHistory,
    AdapterBankRevision,
    AdapterBankStatusReceipt,
    AdapterCompositionManifest,
    AdapterImportRequest,
    AdapterManifest,
    AdapterMaterializationReceipt,
    AdapterResolution,
    AdaptiveLearningReceipt,
    AdaptivePolicy,
    AdvisoryStrategy,
    Alignment,
    AlignmentCalibration,
    ApertureReceipt,
    AuthenticatedCandidate,
    AuthenticatedControllerDataset,
    AuthenticatedExperimentEvidence,
    AuthenticatedKnowledgeState,
    AuthenticatedObservations,
    AuthenticatedObservedDeltas,
    AuthenticatedPrecommitReference,
    AuthenticatedSensitivityArtifacts,
    AuthorityInstance,
    BackendRanking,
    BaseCheckpoint,
    BaselineIntervenedRestoredReport,
    BehavioralBenchmark,
    Benchmark,
    BoundedControlSignal,
    BoundedDelta,
    BrainAnalysisReceipt,
    Bundle,
    CalibrationCases,
    CandidateAdapterArtifact,
    CandidateCheckpoint,
    CandidateDelta,
    CandidateSolution,
    CandidateVector,
    CapabilityBundle,
    CapabilityDiscoveryReport,
    CapabilityIr,
    Catalog,
    CausalCreditReport,
    Checkpoint,
    CoevolutionProgress,
    CognitiveFieldState,
    CompletedAdaptiveSession,
    Config,
    ConsensusState,
    ConsolidatedState,
    ContentConfidenceUpdate,
    ControllerPolicy,
    CounterfactualEvaluations,
    CounterfactualResult,
    CurrentStatePromotionPermit,
    Curvature,
    CycleHistory,
    DeclaredSourceScope,
    DeepInstrumentationEvidence,
    DeltaObservations,
    DenseShadowArtifact,
    DiscoveryCycle,
    DualSpaceAnalysis,
    EligibilitySignal,
    EloRatingUpdate,
    ExecutorDescriptor,
    ExplicitGovernancePolicy,
    Extraction,
    #[serde(rename = "fact/source_observations")]
    FactSourceObservations,
    FieldRoutingDecision,
    ForwardRollbackRevision,
    FrozenReceiverCompiler,
    FrozenReceiverCompilerVerification,
    FunctionalTransportMap,
    Gaps,
    GenerationOrderedDeltaHistory,
    GovernedAuthorization,
    HeldoutTrials,
    HfSnapshot,
    HfWeightMap,
    HoldoutGroups,
    IdentifiabilityReport,
    InternalActivations,
    JobOutcomes,
    KnowledgePlanningDecision,
    KnowledgeState,
    LearnedControllerReceipt,
    LearningFinalizationReceipt,
    LearningPlan,
    LearningTarget,
    Limits,
    LlmRuntime,
    LowRankPolicy,
    LowRankShadowArtifact,
    ManifoldSamples,
    MaterializationReceipt,
    MaterializationRequest,
    MaterializationVerification,
    MeasuredBackendMetrics,
    Measurement,
    ModelEvaluation,
    ModulatedRate,
    ModulePath,
    NegativeExamples,
    NewEvidence,
    Novelty,
    NumericalEvolutionReceipt,
    OperatorEvidenceReceipt,
    OperatorJobRecord,
    OrderedAdapterIds,
    Outcomes,
    PairedActivations,
    PairedOutcomes,
    PastAttempts,
    PolicyRequiredVotes,
    PositiveExamples,
    PrivateAuthorityRoot,
    PromotedStateBinding,
    Prompt,
    Proposals,
    ProtectedMap,
    ProtectedMapReceipt,
    Protection,
    PythagorasReport,
    ReadinessDecision,
    ReceiverBasisBenchmarkReport,
    ReceiverLayout,
    ReceiverPortabilityBenchmarkReport,
    ReceiverSignatureCompilation,
    ReceiverModelProfile,
    RecordedControllerExecution,
    RelationalTransportMap,
    RepresentationEvidenceReceipt,
    RepresentationObservations,
    Request,
    ResidencyDecision,
    ResidencyDecisionReference,
    RevocationRequest,
    Reward,
    RiskBudget,
    RiskPolicy,
    RiskReceipt,
    RollbackRequest,
    RoutingDecision,
    Runner,
    RuntimeAccessProfile,
    #[serde(rename = "runtime_profile.deep_instrumentation")]
    RuntimeProfileDeepInstrumentation,
    #[serde(rename = "runtime_profile.sparse_autoencoder_analysis")]
    RuntimeProfileSparseAutoencoderAnalysis,
    SaeId,
    SaeRelease,
    SbasTrajectory,
    Scenario,
    SealedGateWitnesses,
    SealedInstallRequest,
    SealedRepresentationEvidence,
    Selection,
    Setpoint,
    Shadow,
    ShadowReceipt,
    Shards,
    SingleSafetensorsCheckpoint,
    SkillFields,
    SleepPolicy,
    SleepReceipt,
    Source,
    SourceAnchors,
    SourceFunctionalAnchors,
    SparseFeatureEvidence,
    SparsePolicy,
    SparseShadowArtifact,
    Stability,
    SteeringLayout,
    SteeringPolicy,
    SteeringVectorCandidate,
    StickyRevocation,
    SystemEnvelope,
    Target,
    TargetAnchors,
    TargetCoordinateAnchors,
    TemporalAdvisorySignal,
    TemporalTrackingEvidence,
    ThresholdSignal,
    Tokenizer,
    TomographyGateDecision,
    TomographyReceipt,
    TopologicalManifoldReport,
    TrainingProblem,
    TwoOrMoreLlms,
    UniversalCompilationReceipt,
    UniversalPlanReceipt,
    UniversalPlanRequest,
    Universality,
    UniversalityReceipt,
    ValidationPrompts,
    VaultReceipt,
    VerifiedHistory,
    VerifiedLedgerSnapshot,
    Verifier,
    WeightSnapshotsOrDifferentials,
    WeightTomographyObservation,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactRole {
    ExternalInput,
    Intermediate,
    Terminal,
}

impl ArtifactKind {
    pub fn parse(value: &str) -> BrainResult<Self> {
        match value {
            "activation_events" => Ok(Self::ActivationEvents),
            "activation_steering_shadow_artifact" => Ok(Self::ActivationSteeringShadowArtifact),
            "active_adapter_selection" => Ok(Self::ActiveAdapterSelection),
            "activity_observation" => Ok(Self::ActivityObservation),
            "adapter_bank_history" => Ok(Self::AdapterBankHistory),
            "adapter_bank_revision" => Ok(Self::AdapterBankRevision),
            "adapter_bank_status_receipt" => Ok(Self::AdapterBankStatusReceipt),
            "adapter_composition_manifest" => Ok(Self::AdapterCompositionManifest),
            "adapter_import_request" => Ok(Self::AdapterImportRequest),
            "adapter_manifest" => Ok(Self::AdapterManifest),
            "adapter_materialization_receipt" => Ok(Self::AdapterMaterializationReceipt),
            "adapter_resolution" => Ok(Self::AdapterResolution),
            "adaptive_learning_receipt" => Ok(Self::AdaptiveLearningReceipt),
            "adaptive_policy" => Ok(Self::AdaptivePolicy),
            "advisory_strategy" => Ok(Self::AdvisoryStrategy),
            "alignment" => Ok(Self::Alignment),
            "alignment_calibration" => Ok(Self::AlignmentCalibration),
            "aperture_receipt" => Ok(Self::ApertureReceipt),
            "authenticated_candidate" => Ok(Self::AuthenticatedCandidate),
            "authenticated_controller_dataset" => Ok(Self::AuthenticatedControllerDataset),
            "authenticated_experiment_evidence" => Ok(Self::AuthenticatedExperimentEvidence),
            "authenticated_knowledge_state" => Ok(Self::AuthenticatedKnowledgeState),
            "authenticated_observations" => Ok(Self::AuthenticatedObservations),
            "authenticated_observed_deltas" => Ok(Self::AuthenticatedObservedDeltas),
            "authenticated_precommit_reference" => Ok(Self::AuthenticatedPrecommitReference),
            "authenticated_sensitivity_artifacts" => Ok(Self::AuthenticatedSensitivityArtifacts),
            "authority_instance" => Ok(Self::AuthorityInstance),
            "backend_ranking" => Ok(Self::BackendRanking),
            "base_checkpoint" => Ok(Self::BaseCheckpoint),
            "baseline_intervened_restored_report" => Ok(Self::BaselineIntervenedRestoredReport),
            "behavioral_benchmark" => Ok(Self::BehavioralBenchmark),
            "benchmark" => Ok(Self::Benchmark),
            "bounded_control_signal" => Ok(Self::BoundedControlSignal),
            "bounded_delta" => Ok(Self::BoundedDelta),
            "brain_analysis_receipt" => Ok(Self::BrainAnalysisReceipt),
            "bundle" => Ok(Self::Bundle),
            "calibration_cases" => Ok(Self::CalibrationCases),
            "candidate_adapter_artifact" => Ok(Self::CandidateAdapterArtifact),
            "candidate_checkpoint" => Ok(Self::CandidateCheckpoint),
            "candidate_delta" => Ok(Self::CandidateDelta),
            "candidate_solution" => Ok(Self::CandidateSolution),
            "candidate_vector" => Ok(Self::CandidateVector),
            "capability_bundle" => Ok(Self::CapabilityBundle),
            "capability_discovery_report" => Ok(Self::CapabilityDiscoveryReport),
            "capability_ir" => Ok(Self::CapabilityIr),
            "catalog" => Ok(Self::Catalog),
            "causal_credit_report" => Ok(Self::CausalCreditReport),
            "checkpoint" => Ok(Self::Checkpoint),
            "coevolution_progress" => Ok(Self::CoevolutionProgress),
            "cognitive_field_state" => Ok(Self::CognitiveFieldState),
            "completed_adaptive_session" => Ok(Self::CompletedAdaptiveSession),
            "config" => Ok(Self::Config),
            "consensus_state" => Ok(Self::ConsensusState),
            "consolidated_state" => Ok(Self::ConsolidatedState),
            "content_confidence_update" => Ok(Self::ContentConfidenceUpdate),
            "controller_policy" => Ok(Self::ControllerPolicy),
            "counterfactual_evaluations" => Ok(Self::CounterfactualEvaluations),
            "counterfactual_result" => Ok(Self::CounterfactualResult),
            "current_state_promotion_permit" => Ok(Self::CurrentStatePromotionPermit),
            "curvature" => Ok(Self::Curvature),
            "cycle_history" => Ok(Self::CycleHistory),
            "declared_source_scope" => Ok(Self::DeclaredSourceScope),
            "deep_instrumentation_evidence" => Ok(Self::DeepInstrumentationEvidence),
            "delta_observations" => Ok(Self::DeltaObservations),
            "dense_shadow_artifact" => Ok(Self::DenseShadowArtifact),
            "discovery_cycle" => Ok(Self::DiscoveryCycle),
            "dual_space_analysis" => Ok(Self::DualSpaceAnalysis),
            "eligibility_signal" => Ok(Self::EligibilitySignal),
            "elo_rating_update" => Ok(Self::EloRatingUpdate),
            "executor_descriptor" => Ok(Self::ExecutorDescriptor),
            "explicit_governance_policy" => Ok(Self::ExplicitGovernancePolicy),
            "extraction" => Ok(Self::Extraction),
            "fact/source_observations" => Ok(Self::FactSourceObservations),
            "field_routing_decision" => Ok(Self::FieldRoutingDecision),
            "forward_rollback_revision" => Ok(Self::ForwardRollbackRevision),
            "frozen_receiver_compiler" => Ok(Self::FrozenReceiverCompiler),
            "frozen_receiver_compiler_verification" => Ok(Self::FrozenReceiverCompilerVerification),
            "functional_transport_map" => Ok(Self::FunctionalTransportMap),
            "gaps" => Ok(Self::Gaps),
            "generation_ordered_delta_history" => Ok(Self::GenerationOrderedDeltaHistory),
            "governed_authorization" => Ok(Self::GovernedAuthorization),
            "heldout_trials" => Ok(Self::HeldoutTrials),
            "hf_snapshot" => Ok(Self::HfSnapshot),
            "hf_weight_map" => Ok(Self::HfWeightMap),
            "holdout_groups" => Ok(Self::HoldoutGroups),
            "identifiability_report" => Ok(Self::IdentifiabilityReport),
            "internal_activations" => Ok(Self::InternalActivations),
            "job_outcomes" => Ok(Self::JobOutcomes),
            "knowledge_planning_decision" => Ok(Self::KnowledgePlanningDecision),
            "knowledge_state" => Ok(Self::KnowledgeState),
            "learned_controller_receipt" => Ok(Self::LearnedControllerReceipt),
            "learning_finalization_receipt" => Ok(Self::LearningFinalizationReceipt),
            "learning_plan" => Ok(Self::LearningPlan),
            "learning_target" => Ok(Self::LearningTarget),
            "limits" => Ok(Self::Limits),
            "llm_runtime" => Ok(Self::LlmRuntime),
            "low_rank_policy" => Ok(Self::LowRankPolicy),
            "low_rank_shadow_artifact" => Ok(Self::LowRankShadowArtifact),
            "manifold_samples" => Ok(Self::ManifoldSamples),
            "materialization_receipt" => Ok(Self::MaterializationReceipt),
            "materialization_request" => Ok(Self::MaterializationRequest),
            "materialization_verification" => Ok(Self::MaterializationVerification),
            "measured_backend_metrics" => Ok(Self::MeasuredBackendMetrics),
            "measurement" => Ok(Self::Measurement),
            "model_evaluation" => Ok(Self::ModelEvaluation),
            "modulated_rate" => Ok(Self::ModulatedRate),
            "module_path" => Ok(Self::ModulePath),
            "negative_examples" => Ok(Self::NegativeExamples),
            "new_evidence" => Ok(Self::NewEvidence),
            "novelty" => Ok(Self::Novelty),
            "numerical_evolution_receipt" => Ok(Self::NumericalEvolutionReceipt),
            "operator_evidence_receipt" => Ok(Self::OperatorEvidenceReceipt),
            "operator_job_record" => Ok(Self::OperatorJobRecord),
            "ordered_adapter_ids" => Ok(Self::OrderedAdapterIds),
            "outcomes" => Ok(Self::Outcomes),
            "paired_activations" => Ok(Self::PairedActivations),
            "paired_outcomes" => Ok(Self::PairedOutcomes),
            "past_attempts" => Ok(Self::PastAttempts),
            "policy_required_votes" => Ok(Self::PolicyRequiredVotes),
            "positive_examples" => Ok(Self::PositiveExamples),
            "private_authority_root" => Ok(Self::PrivateAuthorityRoot),
            "promoted_state_binding" => Ok(Self::PromotedStateBinding),
            "prompt" => Ok(Self::Prompt),
            "proposals" => Ok(Self::Proposals),
            "protected_map" => Ok(Self::ProtectedMap),
            "protected_map_receipt" => Ok(Self::ProtectedMapReceipt),
            "protection" => Ok(Self::Protection),
            "pythagoras_report" => Ok(Self::PythagorasReport),
            "readiness_decision" => Ok(Self::ReadinessDecision),
            "receiver_basis_benchmark_report" => Ok(Self::ReceiverBasisBenchmarkReport),
            "receiver_portability_benchmark_report" => Ok(Self::ReceiverPortabilityBenchmarkReport),
            "receiver_signature_compilation" => Ok(Self::ReceiverSignatureCompilation),
            "receiver_layout" => Ok(Self::ReceiverLayout),
            "receiver_model_profile" => Ok(Self::ReceiverModelProfile),
            "recorded_controller_execution" => Ok(Self::RecordedControllerExecution),
            "relational_transport_map" => Ok(Self::RelationalTransportMap),
            "representation_evidence_receipt" => Ok(Self::RepresentationEvidenceReceipt),
            "representation_observations" => Ok(Self::RepresentationObservations),
            "request" => Ok(Self::Request),
            "residency_decision" => Ok(Self::ResidencyDecision),
            "residency_decision_reference" => Ok(Self::ResidencyDecisionReference),
            "revocation_request" => Ok(Self::RevocationRequest),
            "reward" => Ok(Self::Reward),
            "risk_budget" => Ok(Self::RiskBudget),
            "risk_policy" => Ok(Self::RiskPolicy),
            "risk_receipt" => Ok(Self::RiskReceipt),
            "rollback_request" => Ok(Self::RollbackRequest),
            "routing_decision" => Ok(Self::RoutingDecision),
            "runner" => Ok(Self::Runner),
            "runtime_access_profile" => Ok(Self::RuntimeAccessProfile),
            "runtime_profile.deep_instrumentation" => Ok(Self::RuntimeProfileDeepInstrumentation),
            "runtime_profile.sparse_autoencoder_analysis" => {
                Ok(Self::RuntimeProfileSparseAutoencoderAnalysis)
            }
            "sae_id" => Ok(Self::SaeId),
            "sae_release" => Ok(Self::SaeRelease),
            "sbas_trajectory" => Ok(Self::SbasTrajectory),
            "scenario" => Ok(Self::Scenario),
            "sealed_gate_witnesses" => Ok(Self::SealedGateWitnesses),
            "sealed_install_request" => Ok(Self::SealedInstallRequest),
            "sealed_representation_evidence" => Ok(Self::SealedRepresentationEvidence),
            "selection" => Ok(Self::Selection),
            "setpoint" => Ok(Self::Setpoint),
            "shadow" => Ok(Self::Shadow),
            "shadow_receipt" => Ok(Self::ShadowReceipt),
            "shards" => Ok(Self::Shards),
            "single_safetensors_checkpoint" => Ok(Self::SingleSafetensorsCheckpoint),
            "skill_fields" => Ok(Self::SkillFields),
            "sleep_policy" => Ok(Self::SleepPolicy),
            "sleep_receipt" => Ok(Self::SleepReceipt),
            "source" => Ok(Self::Source),
            "source_anchors" => Ok(Self::SourceAnchors),
            "source_functional_anchors" => Ok(Self::SourceFunctionalAnchors),
            "sparse_feature_evidence" => Ok(Self::SparseFeatureEvidence),
            "sparse_policy" => Ok(Self::SparsePolicy),
            "sparse_shadow_artifact" => Ok(Self::SparseShadowArtifact),
            "stability" => Ok(Self::Stability),
            "steering_layout" => Ok(Self::SteeringLayout),
            "steering_policy" => Ok(Self::SteeringPolicy),
            "steering_vector_candidate" => Ok(Self::SteeringVectorCandidate),
            "sticky_revocation" => Ok(Self::StickyRevocation),
            "system_envelope" => Ok(Self::SystemEnvelope),
            "target" => Ok(Self::Target),
            "target_anchors" => Ok(Self::TargetAnchors),
            "target_coordinate_anchors" => Ok(Self::TargetCoordinateAnchors),
            "temporal_advisory_signal" => Ok(Self::TemporalAdvisorySignal),
            "temporal_tracking_evidence" => Ok(Self::TemporalTrackingEvidence),
            "threshold_signal" => Ok(Self::ThresholdSignal),
            "tokenizer" => Ok(Self::Tokenizer),
            "tomography_gate_decision" => Ok(Self::TomographyGateDecision),
            "tomography_receipt" => Ok(Self::TomographyReceipt),
            "topological_manifold_report" => Ok(Self::TopologicalManifoldReport),
            "training_problem" => Ok(Self::TrainingProblem),
            "two_or_more_llms" => Ok(Self::TwoOrMoreLlms),
            "universal_compilation_receipt" => Ok(Self::UniversalCompilationReceipt),
            "universal_plan_receipt" => Ok(Self::UniversalPlanReceipt),
            "universal_plan_request" => Ok(Self::UniversalPlanRequest),
            "universality" => Ok(Self::Universality),
            "universality_receipt" => Ok(Self::UniversalityReceipt),
            "validation_prompts" => Ok(Self::ValidationPrompts),
            "vault_receipt" => Ok(Self::VaultReceipt),
            "verified_history" => Ok(Self::VerifiedHistory),
            "verified_ledger_snapshot" => Ok(Self::VerifiedLedgerSnapshot),
            "verifier" => Ok(Self::Verifier),
            "weight_snapshots_or_differentials" => Ok(Self::WeightSnapshotsOrDifferentials),
            "weight_tomography_observation" => Ok(Self::WeightTomographyObservation),
            other => Err(BrainError::Invalid(format!("executor_artifact_kind_unknown:{other}"))),
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::ActivationEvents => "activation_events",
            Self::ActivationSteeringShadowArtifact => "activation_steering_shadow_artifact",
            Self::ActiveAdapterSelection => "active_adapter_selection",
            Self::ActivityObservation => "activity_observation",
            Self::AdapterBankHistory => "adapter_bank_history",
            Self::AdapterBankRevision => "adapter_bank_revision",
            Self::AdapterBankStatusReceipt => "adapter_bank_status_receipt",
            Self::AdapterCompositionManifest => "adapter_composition_manifest",
            Self::AdapterImportRequest => "adapter_import_request",
            Self::AdapterManifest => "adapter_manifest",
            Self::AdapterMaterializationReceipt => "adapter_materialization_receipt",
            Self::AdapterResolution => "adapter_resolution",
            Self::AdaptiveLearningReceipt => "adaptive_learning_receipt",
            Self::AdaptivePolicy => "adaptive_policy",
            Self::AdvisoryStrategy => "advisory_strategy",
            Self::Alignment => "alignment",
            Self::AlignmentCalibration => "alignment_calibration",
            Self::ApertureReceipt => "aperture_receipt",
            Self::AuthenticatedCandidate => "authenticated_candidate",
            Self::AuthenticatedControllerDataset => "authenticated_controller_dataset",
            Self::AuthenticatedExperimentEvidence => "authenticated_experiment_evidence",
            Self::AuthenticatedKnowledgeState => "authenticated_knowledge_state",
            Self::AuthenticatedObservations => "authenticated_observations",
            Self::AuthenticatedObservedDeltas => "authenticated_observed_deltas",
            Self::AuthenticatedPrecommitReference => "authenticated_precommit_reference",
            Self::AuthenticatedSensitivityArtifacts => "authenticated_sensitivity_artifacts",
            Self::AuthorityInstance => "authority_instance",
            Self::BackendRanking => "backend_ranking",
            Self::BaseCheckpoint => "base_checkpoint",
            Self::BaselineIntervenedRestoredReport => "baseline_intervened_restored_report",
            Self::BehavioralBenchmark => "behavioral_benchmark",
            Self::Benchmark => "benchmark",
            Self::BoundedControlSignal => "bounded_control_signal",
            Self::BoundedDelta => "bounded_delta",
            Self::BrainAnalysisReceipt => "brain_analysis_receipt",
            Self::Bundle => "bundle",
            Self::CalibrationCases => "calibration_cases",
            Self::CandidateAdapterArtifact => "candidate_adapter_artifact",
            Self::CandidateCheckpoint => "candidate_checkpoint",
            Self::CandidateDelta => "candidate_delta",
            Self::CandidateSolution => "candidate_solution",
            Self::CandidateVector => "candidate_vector",
            Self::CapabilityBundle => "capability_bundle",
            Self::CapabilityDiscoveryReport => "capability_discovery_report",
            Self::CapabilityIr => "capability_ir",
            Self::Catalog => "catalog",
            Self::CausalCreditReport => "causal_credit_report",
            Self::Checkpoint => "checkpoint",
            Self::CoevolutionProgress => "coevolution_progress",
            Self::CognitiveFieldState => "cognitive_field_state",
            Self::CompletedAdaptiveSession => "completed_adaptive_session",
            Self::Config => "config",
            Self::ConsensusState => "consensus_state",
            Self::ConsolidatedState => "consolidated_state",
            Self::ContentConfidenceUpdate => "content_confidence_update",
            Self::ControllerPolicy => "controller_policy",
            Self::CounterfactualEvaluations => "counterfactual_evaluations",
            Self::CounterfactualResult => "counterfactual_result",
            Self::CurrentStatePromotionPermit => "current_state_promotion_permit",
            Self::Curvature => "curvature",
            Self::CycleHistory => "cycle_history",
            Self::DeclaredSourceScope => "declared_source_scope",
            Self::DeepInstrumentationEvidence => "deep_instrumentation_evidence",
            Self::DeltaObservations => "delta_observations",
            Self::DenseShadowArtifact => "dense_shadow_artifact",
            Self::DiscoveryCycle => "discovery_cycle",
            Self::DualSpaceAnalysis => "dual_space_analysis",
            Self::EligibilitySignal => "eligibility_signal",
            Self::EloRatingUpdate => "elo_rating_update",
            Self::ExecutorDescriptor => "executor_descriptor",
            Self::ExplicitGovernancePolicy => "explicit_governance_policy",
            Self::Extraction => "extraction",
            Self::FactSourceObservations => "fact/source_observations",
            Self::FieldRoutingDecision => "field_routing_decision",
            Self::ForwardRollbackRevision => "forward_rollback_revision",
            Self::FrozenReceiverCompiler => "frozen_receiver_compiler",
            Self::FrozenReceiverCompilerVerification => "frozen_receiver_compiler_verification",
            Self::FunctionalTransportMap => "functional_transport_map",
            Self::Gaps => "gaps",
            Self::GenerationOrderedDeltaHistory => "generation_ordered_delta_history",
            Self::GovernedAuthorization => "governed_authorization",
            Self::HeldoutTrials => "heldout_trials",
            Self::HfSnapshot => "hf_snapshot",
            Self::HfWeightMap => "hf_weight_map",
            Self::HoldoutGroups => "holdout_groups",
            Self::IdentifiabilityReport => "identifiability_report",
            Self::InternalActivations => "internal_activations",
            Self::JobOutcomes => "job_outcomes",
            Self::KnowledgePlanningDecision => "knowledge_planning_decision",
            Self::KnowledgeState => "knowledge_state",
            Self::LearnedControllerReceipt => "learned_controller_receipt",
            Self::LearningFinalizationReceipt => "learning_finalization_receipt",
            Self::LearningPlan => "learning_plan",
            Self::LearningTarget => "learning_target",
            Self::Limits => "limits",
            Self::LlmRuntime => "llm_runtime",
            Self::LowRankPolicy => "low_rank_policy",
            Self::LowRankShadowArtifact => "low_rank_shadow_artifact",
            Self::ManifoldSamples => "manifold_samples",
            Self::MaterializationReceipt => "materialization_receipt",
            Self::MaterializationRequest => "materialization_request",
            Self::MaterializationVerification => "materialization_verification",
            Self::MeasuredBackendMetrics => "measured_backend_metrics",
            Self::Measurement => "measurement",
            Self::ModelEvaluation => "model_evaluation",
            Self::ModulatedRate => "modulated_rate",
            Self::ModulePath => "module_path",
            Self::NegativeExamples => "negative_examples",
            Self::NewEvidence => "new_evidence",
            Self::Novelty => "novelty",
            Self::NumericalEvolutionReceipt => "numerical_evolution_receipt",
            Self::OperatorEvidenceReceipt => "operator_evidence_receipt",
            Self::OperatorJobRecord => "operator_job_record",
            Self::OrderedAdapterIds => "ordered_adapter_ids",
            Self::Outcomes => "outcomes",
            Self::PairedActivations => "paired_activations",
            Self::PairedOutcomes => "paired_outcomes",
            Self::PastAttempts => "past_attempts",
            Self::PolicyRequiredVotes => "policy_required_votes",
            Self::PositiveExamples => "positive_examples",
            Self::PrivateAuthorityRoot => "private_authority_root",
            Self::PromotedStateBinding => "promoted_state_binding",
            Self::Prompt => "prompt",
            Self::Proposals => "proposals",
            Self::ProtectedMap => "protected_map",
            Self::ProtectedMapReceipt => "protected_map_receipt",
            Self::Protection => "protection",
            Self::PythagorasReport => "pythagoras_report",
            Self::ReadinessDecision => "readiness_decision",
            Self::ReceiverBasisBenchmarkReport => "receiver_basis_benchmark_report",
            Self::ReceiverPortabilityBenchmarkReport => "receiver_portability_benchmark_report",
            Self::ReceiverSignatureCompilation => "receiver_signature_compilation",
            Self::ReceiverLayout => "receiver_layout",
            Self::ReceiverModelProfile => "receiver_model_profile",
            Self::RecordedControllerExecution => "recorded_controller_execution",
            Self::RelationalTransportMap => "relational_transport_map",
            Self::RepresentationEvidenceReceipt => "representation_evidence_receipt",
            Self::RepresentationObservations => "representation_observations",
            Self::Request => "request",
            Self::ResidencyDecision => "residency_decision",
            Self::ResidencyDecisionReference => "residency_decision_reference",
            Self::RevocationRequest => "revocation_request",
            Self::Reward => "reward",
            Self::RiskBudget => "risk_budget",
            Self::RiskPolicy => "risk_policy",
            Self::RiskReceipt => "risk_receipt",
            Self::RollbackRequest => "rollback_request",
            Self::RoutingDecision => "routing_decision",
            Self::Runner => "runner",
            Self::RuntimeAccessProfile => "runtime_access_profile",
            Self::RuntimeProfileDeepInstrumentation => "runtime_profile.deep_instrumentation",
            Self::RuntimeProfileSparseAutoencoderAnalysis => {
                "runtime_profile.sparse_autoencoder_analysis"
            }
            Self::SaeId => "sae_id",
            Self::SaeRelease => "sae_release",
            Self::SbasTrajectory => "sbas_trajectory",
            Self::Scenario => "scenario",
            Self::SealedGateWitnesses => "sealed_gate_witnesses",
            Self::SealedInstallRequest => "sealed_install_request",
            Self::SealedRepresentationEvidence => "sealed_representation_evidence",
            Self::Selection => "selection",
            Self::Setpoint => "setpoint",
            Self::Shadow => "shadow",
            Self::ShadowReceipt => "shadow_receipt",
            Self::Shards => "shards",
            Self::SingleSafetensorsCheckpoint => "single_safetensors_checkpoint",
            Self::SkillFields => "skill_fields",
            Self::SleepPolicy => "sleep_policy",
            Self::SleepReceipt => "sleep_receipt",
            Self::Source => "source",
            Self::SourceAnchors => "source_anchors",
            Self::SourceFunctionalAnchors => "source_functional_anchors",
            Self::SparseFeatureEvidence => "sparse_feature_evidence",
            Self::SparsePolicy => "sparse_policy",
            Self::SparseShadowArtifact => "sparse_shadow_artifact",
            Self::Stability => "stability",
            Self::SteeringLayout => "steering_layout",
            Self::SteeringPolicy => "steering_policy",
            Self::SteeringVectorCandidate => "steering_vector_candidate",
            Self::StickyRevocation => "sticky_revocation",
            Self::SystemEnvelope => "system_envelope",
            Self::Target => "target",
            Self::TargetAnchors => "target_anchors",
            Self::TargetCoordinateAnchors => "target_coordinate_anchors",
            Self::TemporalAdvisorySignal => "temporal_advisory_signal",
            Self::TemporalTrackingEvidence => "temporal_tracking_evidence",
            Self::ThresholdSignal => "threshold_signal",
            Self::Tokenizer => "tokenizer",
            Self::TomographyGateDecision => "tomography_gate_decision",
            Self::TomographyReceipt => "tomography_receipt",
            Self::TopologicalManifoldReport => "topological_manifold_report",
            Self::TrainingProblem => "training_problem",
            Self::TwoOrMoreLlms => "two_or_more_llms",
            Self::UniversalCompilationReceipt => "universal_compilation_receipt",
            Self::UniversalPlanReceipt => "universal_plan_receipt",
            Self::UniversalPlanRequest => "universal_plan_request",
            Self::Universality => "universality",
            Self::UniversalityReceipt => "universality_receipt",
            Self::ValidationPrompts => "validation_prompts",
            Self::VaultReceipt => "vault_receipt",
            Self::VerifiedHistory => "verified_history",
            Self::VerifiedLedgerSnapshot => "verified_ledger_snapshot",
            Self::Verifier => "verifier",
            Self::WeightSnapshotsOrDifferentials => "weight_snapshots_or_differentials",
            Self::WeightTomographyObservation => "weight_tomography_observation",
        }
    }

    pub fn role(self) -> ArtifactRole {
        match self {
            Self::ActivationEvents => ArtifactRole::ExternalInput,
            Self::ActivationSteeringShadowArtifact => ArtifactRole::Terminal,
            Self::ActiveAdapterSelection => ArtifactRole::Terminal,
            Self::ActivityObservation => ArtifactRole::ExternalInput,
            Self::AdapterBankHistory => ArtifactRole::ExternalInput,
            Self::AdapterBankRevision => ArtifactRole::Intermediate,
            Self::AdapterBankStatusReceipt => ArtifactRole::Terminal,
            Self::AdapterCompositionManifest => ArtifactRole::Terminal,
            Self::AdapterImportRequest => ArtifactRole::ExternalInput,
            Self::AdapterManifest => ArtifactRole::Terminal,
            Self::AdapterMaterializationReceipt => ArtifactRole::Terminal,
            Self::AdapterResolution => ArtifactRole::ExternalInput,
            Self::AdaptiveLearningReceipt => ArtifactRole::Terminal,
            Self::AdaptivePolicy => ArtifactRole::ExternalInput,
            Self::AdvisoryStrategy => ArtifactRole::Terminal,
            Self::Alignment => ArtifactRole::ExternalInput,
            Self::AlignmentCalibration => ArtifactRole::Terminal,
            Self::ApertureReceipt => ArtifactRole::Terminal,
            Self::AuthenticatedCandidate => ArtifactRole::ExternalInput,
            Self::AuthenticatedControllerDataset => ArtifactRole::ExternalInput,
            Self::AuthenticatedExperimentEvidence => ArtifactRole::ExternalInput,
            Self::AuthenticatedKnowledgeState => ArtifactRole::ExternalInput,
            Self::AuthenticatedObservations => ArtifactRole::ExternalInput,
            Self::AuthenticatedObservedDeltas => ArtifactRole::ExternalInput,
            Self::AuthenticatedPrecommitReference => ArtifactRole::ExternalInput,
            Self::AuthenticatedSensitivityArtifacts => ArtifactRole::ExternalInput,
            Self::AuthorityInstance => ArtifactRole::ExternalInput,
            Self::BackendRanking => ArtifactRole::Terminal,
            Self::BaseCheckpoint => ArtifactRole::ExternalInput,
            Self::BaselineIntervenedRestoredReport => ArtifactRole::Terminal,
            Self::BehavioralBenchmark => ArtifactRole::ExternalInput,
            Self::Benchmark => ArtifactRole::ExternalInput,
            Self::BoundedControlSignal => ArtifactRole::Terminal,
            Self::BoundedDelta => ArtifactRole::Terminal,
            Self::BrainAnalysisReceipt => ArtifactRole::Terminal,
            Self::Bundle => ArtifactRole::ExternalInput,
            Self::CalibrationCases => ArtifactRole::ExternalInput,
            Self::CandidateAdapterArtifact => ArtifactRole::Terminal,
            Self::CandidateCheckpoint => ArtifactRole::Terminal,
            Self::CandidateDelta => ArtifactRole::ExternalInput,
            Self::CandidateSolution => ArtifactRole::Terminal,
            Self::CandidateVector => ArtifactRole::ExternalInput,
            Self::CapabilityBundle => ArtifactRole::ExternalInput,
            Self::CapabilityDiscoveryReport => ArtifactRole::Terminal,
            Self::CapabilityIr => ArtifactRole::ExternalInput,
            Self::Catalog => ArtifactRole::ExternalInput,
            Self::CausalCreditReport => ArtifactRole::Terminal,
            Self::Checkpoint => ArtifactRole::ExternalInput,
            Self::CoevolutionProgress => ArtifactRole::Terminal,
            Self::CognitiveFieldState => ArtifactRole::Terminal,
            Self::CompletedAdaptiveSession => ArtifactRole::ExternalInput,
            Self::Config => ArtifactRole::ExternalInput,
            Self::ConsensusState => ArtifactRole::Terminal,
            Self::ConsolidatedState => ArtifactRole::Terminal,
            Self::ContentConfidenceUpdate => ArtifactRole::Terminal,
            Self::ControllerPolicy => ArtifactRole::ExternalInput,
            Self::CounterfactualEvaluations => ArtifactRole::ExternalInput,
            Self::CounterfactualResult => ArtifactRole::Terminal,
            Self::CurrentStatePromotionPermit => ArtifactRole::Intermediate,
            Self::Curvature => ArtifactRole::ExternalInput,
            Self::CycleHistory => ArtifactRole::ExternalInput,
            Self::DeclaredSourceScope => ArtifactRole::ExternalInput,
            Self::DeepInstrumentationEvidence => ArtifactRole::Terminal,
            Self::DeltaObservations => ArtifactRole::ExternalInput,
            Self::DenseShadowArtifact => ArtifactRole::Terminal,
            Self::DiscoveryCycle => ArtifactRole::Terminal,
            Self::DualSpaceAnalysis => ArtifactRole::Terminal,
            Self::EligibilitySignal => ArtifactRole::Terminal,
            Self::EloRatingUpdate => ArtifactRole::Terminal,
            Self::ExecutorDescriptor => ArtifactRole::ExternalInput,
            Self::ExplicitGovernancePolicy => ArtifactRole::ExternalInput,
            Self::Extraction => ArtifactRole::ExternalInput,
            Self::FactSourceObservations => ArtifactRole::ExternalInput,
            Self::FieldRoutingDecision => ArtifactRole::Terminal,
            Self::ForwardRollbackRevision => ArtifactRole::Terminal,
            Self::FrozenReceiverCompiler => ArtifactRole::Intermediate,
            Self::FrozenReceiverCompilerVerification => ArtifactRole::Terminal,
            Self::FunctionalTransportMap => ArtifactRole::Terminal,
            Self::Gaps => ArtifactRole::Terminal,
            Self::GenerationOrderedDeltaHistory => ArtifactRole::ExternalInput,
            Self::GovernedAuthorization => ArtifactRole::ExternalInput,
            Self::HeldoutTrials => ArtifactRole::ExternalInput,
            Self::HfSnapshot => ArtifactRole::ExternalInput,
            Self::HfWeightMap => ArtifactRole::ExternalInput,
            Self::HoldoutGroups => ArtifactRole::ExternalInput,
            Self::IdentifiabilityReport => ArtifactRole::Terminal,
            Self::InternalActivations => ArtifactRole::ExternalInput,
            Self::JobOutcomes => ArtifactRole::ExternalInput,
            Self::KnowledgePlanningDecision => ArtifactRole::Terminal,
            Self::KnowledgeState => ArtifactRole::ExternalInput,
            Self::LearnedControllerReceipt => ArtifactRole::Terminal,
            Self::LearningFinalizationReceipt => ArtifactRole::Terminal,
            Self::LearningPlan => ArtifactRole::Terminal,
            Self::LearningTarget => ArtifactRole::ExternalInput,
            Self::Limits => ArtifactRole::ExternalInput,
            Self::LlmRuntime => ArtifactRole::ExternalInput,
            Self::LowRankPolicy => ArtifactRole::ExternalInput,
            Self::LowRankShadowArtifact => ArtifactRole::Terminal,
            Self::ManifoldSamples => ArtifactRole::ExternalInput,
            Self::MaterializationReceipt => ArtifactRole::Terminal,
            Self::MaterializationRequest => ArtifactRole::ExternalInput,
            Self::MaterializationVerification => ArtifactRole::Terminal,
            Self::MeasuredBackendMetrics => ArtifactRole::ExternalInput,
            Self::Measurement => ArtifactRole::ExternalInput,
            Self::ModelEvaluation => ArtifactRole::Terminal,
            Self::ModulatedRate => ArtifactRole::Terminal,
            Self::ModulePath => ArtifactRole::ExternalInput,
            Self::NegativeExamples => ArtifactRole::ExternalInput,
            Self::NewEvidence => ArtifactRole::ExternalInput,
            Self::Novelty => ArtifactRole::ExternalInput,
            Self::NumericalEvolutionReceipt => ArtifactRole::Terminal,
            Self::OperatorEvidenceReceipt => ArtifactRole::Terminal,
            Self::OperatorJobRecord => ArtifactRole::Terminal,
            Self::OrderedAdapterIds => ArtifactRole::ExternalInput,
            Self::Outcomes => ArtifactRole::ExternalInput,
            Self::PairedActivations => ArtifactRole::ExternalInput,
            Self::PairedOutcomes => ArtifactRole::ExternalInput,
            Self::PastAttempts => ArtifactRole::ExternalInput,
            Self::PolicyRequiredVotes => ArtifactRole::ExternalInput,
            Self::PositiveExamples => ArtifactRole::ExternalInput,
            Self::PrivateAuthorityRoot => ArtifactRole::ExternalInput,
            Self::PromotedStateBinding => ArtifactRole::ExternalInput,
            Self::Prompt => ArtifactRole::ExternalInput,
            Self::Proposals => ArtifactRole::Terminal,
            Self::ProtectedMap => ArtifactRole::Terminal,
            Self::ProtectedMapReceipt => ArtifactRole::Terminal,
            Self::Protection => ArtifactRole::ExternalInput,
            Self::PythagorasReport => ArtifactRole::Terminal,
            Self::ReadinessDecision => ArtifactRole::Terminal,
            Self::ReceiverBasisBenchmarkReport => ArtifactRole::Terminal,
            Self::ReceiverPortabilityBenchmarkReport => ArtifactRole::Terminal,
            Self::ReceiverSignatureCompilation => ArtifactRole::Terminal,
            Self::ReceiverLayout => ArtifactRole::ExternalInput,
            Self::ReceiverModelProfile => ArtifactRole::Terminal,
            Self::RecordedControllerExecution => ArtifactRole::Terminal,
            Self::RelationalTransportMap => ArtifactRole::Terminal,
            Self::RepresentationEvidenceReceipt => ArtifactRole::Terminal,
            Self::RepresentationObservations => ArtifactRole::ExternalInput,
            Self::Request => ArtifactRole::ExternalInput,
            Self::ResidencyDecision => ArtifactRole::Terminal,
            Self::ResidencyDecisionReference => ArtifactRole::Terminal,
            Self::RevocationRequest => ArtifactRole::ExternalInput,
            Self::Reward => ArtifactRole::ExternalInput,
            Self::RiskBudget => ArtifactRole::ExternalInput,
            Self::RiskPolicy => ArtifactRole::ExternalInput,
            Self::RiskReceipt => ArtifactRole::Terminal,
            Self::RollbackRequest => ArtifactRole::ExternalInput,
            Self::RoutingDecision => ArtifactRole::Terminal,
            Self::Runner => ArtifactRole::ExternalInput,
            Self::RuntimeAccessProfile => ArtifactRole::Terminal,
            Self::RuntimeProfileDeepInstrumentation => ArtifactRole::ExternalInput,
            Self::RuntimeProfileSparseAutoencoderAnalysis => ArtifactRole::ExternalInput,
            Self::SaeId => ArtifactRole::ExternalInput,
            Self::SaeRelease => ArtifactRole::ExternalInput,
            Self::SbasTrajectory => ArtifactRole::Terminal,
            Self::Scenario => ArtifactRole::ExternalInput,
            Self::SealedGateWitnesses => ArtifactRole::ExternalInput,
            Self::SealedInstallRequest => ArtifactRole::ExternalInput,
            Self::SealedRepresentationEvidence => ArtifactRole::ExternalInput,
            Self::Selection => ArtifactRole::ExternalInput,
            Self::Setpoint => ArtifactRole::ExternalInput,
            Self::Shadow => ArtifactRole::ExternalInput,
            Self::ShadowReceipt => ArtifactRole::Terminal,
            Self::Shards => ArtifactRole::ExternalInput,
            Self::SingleSafetensorsCheckpoint => ArtifactRole::Terminal,
            Self::SkillFields => ArtifactRole::Intermediate,
            Self::SleepPolicy => ArtifactRole::ExternalInput,
            Self::SleepReceipt => ArtifactRole::Terminal,
            Self::Source => ArtifactRole::ExternalInput,
            Self::SourceAnchors => ArtifactRole::ExternalInput,
            Self::SourceFunctionalAnchors => ArtifactRole::ExternalInput,
            Self::SparseFeatureEvidence => ArtifactRole::Terminal,
            Self::SparsePolicy => ArtifactRole::ExternalInput,
            Self::SparseShadowArtifact => ArtifactRole::Terminal,
            Self::Stability => ArtifactRole::ExternalInput,
            Self::SteeringLayout => ArtifactRole::ExternalInput,
            Self::SteeringPolicy => ArtifactRole::ExternalInput,
            Self::SteeringVectorCandidate => ArtifactRole::Terminal,
            Self::StickyRevocation => ArtifactRole::Terminal,
            Self::SystemEnvelope => ArtifactRole::Terminal,
            Self::Target => ArtifactRole::ExternalInput,
            Self::TargetAnchors => ArtifactRole::ExternalInput,
            Self::TargetCoordinateAnchors => ArtifactRole::ExternalInput,
            Self::TemporalAdvisorySignal => ArtifactRole::Terminal,
            Self::TemporalTrackingEvidence => ArtifactRole::Terminal,
            Self::ThresholdSignal => ArtifactRole::Terminal,
            Self::Tokenizer => ArtifactRole::ExternalInput,
            Self::TomographyGateDecision => ArtifactRole::Terminal,
            Self::TomographyReceipt => ArtifactRole::Terminal,
            Self::TopologicalManifoldReport => ArtifactRole::Terminal,
            Self::TrainingProblem => ArtifactRole::ExternalInput,
            Self::TwoOrMoreLlms => ArtifactRole::ExternalInput,
            Self::UniversalCompilationReceipt => ArtifactRole::Terminal,
            Self::UniversalPlanReceipt => ArtifactRole::Intermediate,
            Self::UniversalPlanRequest => ArtifactRole::ExternalInput,
            Self::Universality => ArtifactRole::ExternalInput,
            Self::UniversalityReceipt => ArtifactRole::Terminal,
            Self::ValidationPrompts => ArtifactRole::ExternalInput,
            Self::VaultReceipt => ArtifactRole::Terminal,
            Self::VerifiedHistory => ArtifactRole::ExternalInput,
            Self::VerifiedLedgerSnapshot => ArtifactRole::Terminal,
            Self::Verifier => ArtifactRole::ExternalInput,
            Self::WeightSnapshotsOrDifferentials => ArtifactRole::ExternalInput,
            Self::WeightTomographyObservation => ArtifactRole::Terminal,
        }
    }
}
